### Print all employees
GET http://localhost:8080/employee
Accept: application/json

### Get all employees
GET http://localhost:8080/departments/all
Accept: application/json

### Get employees by department
GET http://localhost:8080/departments/all?departmentId=4
Accept: application/json

### Print an employee with max salary
GET http://localhost:8080/employee/max-salary
Accept: application/json

### Print total monthly salary
GET http://localhost:8080/employee/total-salary
Accept: application/json

### Add Ivan Ivanov Dprt1
GET http://localhost:8080/employee/add?firstName=шvan&lastName=IККККnov&salary=25000&departmentId=2
Accept: application/json

### Add Petr Petrov Dprt1
GET http://localhost:8080/employee/add?firstName= FrFFFdd &lastName=pETRov&salary=45000&departmentId=3
Accept: application/json

### Add Sidor Sidorov Dprt1
GET http://localhost:8080/employee/add?firstName=SIDOR&lastName=  sidoROV   &salary=45000&departmentId=1
Accept: application/json

### Find Sidor Sidorov
GET http://localhost:8080/employee/find?firstName=Sidor&lastName=Sidorov
Accept: application/json

### Set salary - Sidor Sidorov
GET http://localhost:8080/employee/set-salary?firstName=Sidor&lastName=Sidorov&salary=55000
Accept: application/json

### Remove by fullname
GET http://localhost:8080/employee/remove?firstName=Sidor&lastName=Sidorov
Accept: application/json